# Generated by Django 4.2.16 on 2026-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_fooddonation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude captured at delivery', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude captured at delivery', max_digits=11, null=True),
        ),
    ]
